=== travelpaq/Connect-SDK-META-PHP/src/json/schemas/input/searchData.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Esquema de validación para parámetros de getPackageList.",
  "description": "Este esquema contiene los datos que se reciben como parámetro de entrada para el método getPackageList.",
  "properties": {
    "order_field": {
      "type": "string",
      "enum": ["PRICE","DEPARTURE_DATE"],
      "title": "Campo  que marcará orden de resultados.",
      "description": "Atributo de paquete por el cual se establecerá el orden de los resultados."
    },
    "order_type": {
      "type": "string",
      "enum": ["ASC","DESC"],
      "title": "Criterio de orden de resultados",
      "description": "Criterio de orden de resultados ascendente o descendente."
    },
    "currency": {
      "type": "string",
      "enum": ["EUR","USD","ARS"],
      "title": "Tipo de cambio de paquetes.",
      "description": "Especifica el tipo de cambio que tendrán los paquetes retornadoss por el getPackageList."
    },
    "origin_place": {
      "type": "string",
      "minLength": 2,
      "maxLength": 3,
      "title": "Ciudad de origen.",
      "description": "Ciudad de la cual el pasajeros desean comenzar el viaje."
    },
    "destination_place": {
      "type": "string",
      "minLength": 2,
      "maxLength": 3,
      "title": "Ciudad de destino.",
      "description": "Ciudad a la cual el pasajeros desean viajar."      
    },
    "month_departure": {
      "type": "integer",
      "minimum": 1,
      "maximum": 12,
      "title": "Mes de salida.",
      "description": "Mes en el cual el pasajeros desean salir."
    },
    "year_departure": {
      "type": "integer",
      "title": "Año de salida.",
      "description": "Junto con month_departure forman el mes en que el pasajeros desean salir."
    },
    "Room": {
        "type": "array",
        "title": "Habitación.",
        "description": " .",
        "items": {
          "adult": {
            "type": "integer",
            "minimum": 1,
            "maximum": 8,
            "title": "Adultos de la habitación.",
            "description": "Cantidad de adultos que ocupan la habitación."
          },
          "Children": {
            "type": "array",
            "title": "Niños de la habitación.",
            "description": " .",
            "items": {
              "type": "object",
              "title": "Un niño de la habitación.",
              "description": " .",
              "properties": {
                "age": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 18,
                  "title": "Edad del niño."
                }
              }
            }
          }
        },
        "required": [
          "adult",
          "Children"
        ]
     }
  },
  "required": [
    "order_type",
    "order_field",
    "currency",
    "origin_place",
    "destination_place",
    "month_departure",
    "year_departure",
    "Room"
  ]
}

=== travelpaq/Connect-SDK-META-PHP/src/json/examples/input/getPackageList.example.json
{
	"order_type":"ASC",
    "order_field":"PRICE",
    "currency":"ARS",
    "origin_place":"EZE",
    "destination_place":"CUN",
    "month_departure":12,
    "year_departure":2016,
    "Room":
    [
    	{
    		"adult":2,
    		"Children":
    		[
    			{
    				"age":3
    			},
    			{
    				"age":14
    			}
    		]
    	}
    ]
}
